### ISSUE TITLE
The absolute URIs provided do not have the same host/scheme

### ISSUE THREAD

**Issue by follesoe** [DecaTec/Portable-WebDAV-Library#34] opened 2017-04-04 10:49 UTC
Getting the `The absolute URIs provided do not have the same host/scheme` exception when running the following code on Xamarin iOS:

```csharp
var webDavSession = new WebDavSession(new Uri("http://localhost:5050/"), new NetworkCredential());
var items = await webDavSession.ListAsync(@"packages/");
return items.Select(i => i.Name).ToList();
```

**Comment by DecaTec** [comment] 2017-04-04 16:16
Unfortunately I don't have a Mac, so I can't find out what's the problem here (can't debug).
On Windows, I cannot reproduce this error.

The part where the exception is thrown is here:
````cs
if (uri1.IsAbsoluteUri && uri2.IsAbsoluteUri && (uri1.Scheme != uri2.Scheme || uri1.Host != uri2.Host))
                throw new ArgumentException("The absolute URIs provided do not have the same host/scheme");
````
- `uri1` is *http://localhost:5050/*
- `uri2` is */packages*

Could you help me evaluating the if statement on a Mac?
Maybe some `Uri` property does not behave as expected.

Or is there any way to debug an iOS app without having Mac hardware?

**Comment by follesoe** [comment] 2017-04-05 09:43
Executing the following test on Xamarin.iOS throws the exception (as expected, so you're right - this is where the bug is):

```csharp
[Test]
public void Uri_bug()
{
	var uri1 = new Uri("http://localhost:5050/");
	var uri2 = new Uri("/packages");

	if(uri1.IsAbsoluteUri && uri2.IsAbsoluteUri && (uri1.Scheme != uri2.Scheme || uri1.Host != uri2.Host))
		throw new ArgumentException("The absolute URIs provided do not have the same host/scheme");
}
```

If I check the scheme, the following test past, which shows that `/packages` gets a scheme of `file` on Xamarin.iOS (and I expect mono in general).

```csharp
[Test]
public void Comparing_uri_scheme()
{
	var uri1 = new Uri("http://localhost:5050/");
	var uri2 = new Uri("/packages");

	Assert.AreEqual("http", uri1.Scheme);
	Assert.AreEqual("file", uri2.Scheme);
}
```

So one way to test this would be to build/run the code on the Mono runtime instead of .NET Core CLR or full .NET. You can install Mono on a Windows machine.

**Comment by DecaTec** [comment] 2017-04-05 16:48
OK, good catch:
`var x = new Uri("/package", UriKind.RelativeOrAbsolute)` has a different behavior in Xamarin/Mono as on Windows.
On Xamarin, it really creates a absolute Uri with scheme `file`.

Here's the quick fix which will possibly work for you:
````cs
var webDavSession = new WebDavSession(new Uri("http://localhost:5050/"), new NetworkCredential());
var items = await webDavSession.ListAsync(new Uri("packages/", UriKind.Relative);
return items.Select(i => i.Name).ToList();
````

But I have to find a better solution for this case.

**Comment by DecaTec** [comment] 2017-04-05 18:14
I came up with a solution which should fit for all platforms without having to do any code changes for existing projects (see https://github.com/DecaTec/Portable-WebDAV-Library/commit/d288c3602cbc1e667283d143375934a9e98c3a55).
The preview for 0.7.1.0-beta1 is available at [MyGet](https://www.myget.org/feed/decatec-preview/package/nuget/PortableWebDavLibrary/0.7.1-beta1) which should fix this issue.

Could you please have a look at the preview? I'll prepare for a new release when it also works for Xamarin/iOS.

**Comment by follesoe** [comment] 2017-04-05 19:03
This test, using `0.7.1.0-beta1` from MyGet still yields the `The absolute URIs provided do not have the same host/scheme` exception:

```csharp
[Test]
public void List_folder_content()
{
	var session = new WebDavSession(new Uri("http://localhost:5050/"), new NetworkCredential());
	var files = session.ListAsync(new Uri("/packages")).Result;

	Assert.AreEqual(files.Count, 10);
}
```

Passing `UriKind.Relative` avoids the exception.

My package file contains:

```xml
<package id="PortableWebDavLibrary" version="0.7.1-beta1" targetFramework="xamarinios10" />
```

And I made sure to install it from the custom myget feed.

**Comment by follesoe** [comment] 2017-04-05 19:15
Actually, after getting the test to run it also fails when passing in `UriKind.Relative`:

```csharp
[Test]
public void List_folder_content()
{
	AsyncContext.Run(async () =>
	{
		var rootUri = new Uri("http://localhost:5050", UriKind.Absolute);
		var folderUri = new Uri("/packages", UriKind.Relative);

		Assert.IsTrue(rootUri.IsAbsoluteUri);
		Assert.IsFalse(folderUri.IsAbsoluteUri);

		var session = new WebDavSession(rootUri, new NetworkCredential());
		var files = await session.ListAsync(folderUri);
		Assert.AreEqual(files.Count, 10);
	});
}
```

So the first Uri is absolute, while the second is. Despite that; the code path ends up with the same exception, so some where inside the libs new Uri's must be created that turns them into absolute Uri's which in turn will try to compare the scheme.

I got about 60 compile errors on VS2017 preview with .NET Core 1.0.1 SDK on Mac, so not quite there where I can properly debug the lib on Mac.

**Comment by DecaTec** [comment] 2017-04-05 19:23
Thanks for the quick response.
What about this, does it work?
```csharp
[Test]
public void List_folder_content()
{
	var session = new WebDavSession(new Uri("http://localhost:5050/"), new NetworkCredential());
	var files = session.ListAsync("/packages").Result;

	Assert.AreEqual(files.Count, 10);
}
```

The problem here: You have to avoid using the Uri ctor with "/folder" and expecting that this represents a relative Uri. The runtime of Xamarin/Mono will always create an absolute Uri with the scheme "file" here. Imho that's not the expected behavior, but can't be avoided.

You can always use `UriHelper.CreateUriFromUrl` to create a Uri which should be correct in our case.

Edit: I have to take a look at the second issue tomorrow.

**Comment by follesoe** [comment] 2017-04-05 19:30
Passing a string to `ListAsync("/packages")`, or `UriHelper.CreateUriFromUrl("/packages")` both end up with same scheme argument exception.

**Comment by follesoe** [comment] 2017-04-05 19:31
Ah, right, for the `CreateUriFromUrl` I have to pass the full URL, right?

**Comment by DecaTec** [comment] 2017-04-06 08:02
Was a problem when creating the list of `WebDavSessionListItem` on `ListAsync`.
[v0.7.1.0-beta2](https://www.myget.org/feed/decatec-preview/package/nuget/PortableWebDavLibrary/0.7.1-beta2) now available on MyGet.

Please give it a try.

**Comment by DecaTec** [comment] 2017-04-13 13:40
Should be resolved by now and will be part of v0.8.0.0 (I'll skip v0.7.1.0 as there are quite a lot of changes since v0.7.0.0).

**Closed as completed by DecaTec** 2017-04-13 13:40 UTC
Labels: xamarin

**Comment by follesoe** [comment] 2017-04-17 19:14
Excellent, just wan't to confirm that the most current release works fine on Xamarin.iOS.

**Comment by DecaTec** [comment] 2017-04-17 20:14
Great, thanks for your feedback! :+1:
