### ISSUE TITLE
Problem with empty loop in async operations

### ISSUE THREAD

**Issue by milkin-vl** [DecaTec/Portable-WebDAV-Library#60] opened 2017-12-27 04:44 UTC
Hello, dear developer. I have problem.

For example, I set webdav session timeout to 1 minutes. Then i call ExistsAsync from webdav session. And if this request is long time, my app begins to consume 20% processor time. And it is problem if my app works in several threads.

Such an impression that in webdav session wait we have empty cycle like

while (condition)
;

without any pauses for careful about processor.

**Comment by milkin-vl** [comment] 2017-12-27 04:48
Oh, probably it's issue on my side and i need create so pauses in wait tasks. Sorry, close issue.

**Comment by milkin-vl** [comment] 2017-12-27 05:00
No, i checked this issue and problem on side method ExistsAsync. While it is work (in long request time, when problems on webdav server) we have consuming 20% processor time.

**Comment by DecaTec** [comment] 2017-12-27 11:27
I cannot reproduce the issue on my side.
Internally, I simply use a `HttpRequestMessage` with `HttpMethod.Head` from the `HttpClient` the `WebDavClient` is based on:
```
var requestMethod = new HttpRequestMessage(HttpMethod.Head, requestUri);
SetHttpVersion(requestMethod);
return this.SendAsync(requestMethod, completionOption, cancellationToken);
```

Could you please verify that you run into the same issue when using a `HttpClient` directly shown with the code above (ignore the `SetHttpVersion` method)? So something like:
```
HttpClient httpClient = new HttpClient();
HttpRequestMessage request =  new HttpRequestMessage(HttpMethod.Head, new Uri("http://myserver.com/webdav/MyFile.txt"));
HttpResponseMessage response = await httpClient.SendAsync(request);
```
What platform you are using?

**Comment by milkin-vl** [comment] 2017-12-28 01:43
I use .Net Framework 4.5.

Unfortunately i could not make problem so small as you offer.

But fiddler shown me that:
- starting at some point webdav server forcibly close my connection (because free space is ended) but in my logic code i dont now about it and my next attempts to work with connection (for example call ЕxistAsync) bring me so much processor time (call ExistAsync hangs in this time on several minutes).

**Comment by DecaTec** [comment] 2017-12-28 09:03
If I got it right, a single call (e.g. `ExistsAsync`) works, but subsequent calls will fail when there's no free space on the server left.
The library does not use only one connection which is left opened for a specific time, but every call (copy, delete, exists, etc.) opens a new connection  (REST-like).

So for me, it sounds more like a server side problem. Which WebDAV server you are using? Have you checked the server logs already?

**Comment by milkin-vl** [comment] 2017-12-28 09:10
It is about https://disk.yandex.com/ (free 10gb).
It is very popular cloud service in Russia. So i can not see their logs.
I believe that server may be change its behavior when free space finished, but i cant understand why our client code begin take so much processor time (whatever would happen on webdav server).

**Comment by DecaTec** [comment] 2017-12-28 12:12
OK, without the logs, it's difficult to guess where the problem is.
Have you tried to analyze the CPU usage a little more (see [here](https://blogs.msdn.microsoft.com/visualstudio/2016/02/15/analyze-cpu-memory-while-debugging/)).

When I have to guess, it's the call to `SendAsync` of the underlying `HttpClient` which gets blocked somehow on the server side.

**Comment by milkin-vl** [comment] 2017-12-29 04:50
Unfortunately i could not analyze CPU usage. It is tell me that much time in external code. My solution - stop attempts after first failed upload.

But i have another one question about CPU usage. I noticed splash (rapid increase) CPU usage at the begining execution UploadFileAsync. It is directly depends on size of uploading files. For example when i try to upload file with size 500 MB i get CPU usage 25-30-40% during ~10 second and then my process use ~0% of cpu usage all other uploading time. On small files (~50 MB) CPU usage at the begining upload ~15% during several seconds.

Is it normal behavior? Is it possible to do anything to avoid so big CPU usage, make it more smooth?

**Comment by DecaTec** [comment] 2017-12-29 08:52
I also cannot reproduce high CPU load while uploading large files. I've tried to upload a file with 1.5 GB and the CPU load was constantly low (max. 10%).
I cannot explain why you see a high CPU load here, because all what is done in the library is opening a `Stream` (readonly) and using it as content for the PUT operation.

Do you use async/await correctly? The behavior of the application should always be "smooth" when using such async operations.
Do you also have high CPU load when opening the file stream for yourself and uploading it with a simple `HttpClient` call?
Silly question: What hardware you're on?

I'll close the issue because it doesn't seem to be a general problem with the library. But feel free to investigate your issue a little more, perhaps we can sort it out.

**Closed as completed by DecaTec** 2017-12-29 08:52 UTC

**Comment by milkin-vl** [comment] 2017-12-29 23:29
Thanks for your help! I will collect more info and experience about this situation and write here after holidays.

**Comment by milkin-vl** [comment] 2018-01-01 10:41
Sorry, it was my mistake. Running Fiddler application was real reason big CPU usage by my application on uploadfileasync. This behavior was confirmed with using HttpClient and PutAsync.

When Fiddler is off application CPU usage is normal.

**Comment by DecaTec** [comment] 2018-01-01 14:40
OK, then we have the reason for the high CPU load.

Thanks for sharing the experience.
